name: Update Ulasan Playstore

on:
  schedule:
    - cron: '0 18 * * *'   # 01:00 WIB
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # WAJIB agar bisa push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install library
        run: pip install google-play-scraper pandas

      - name: Run script
        run: python ambil_ulasan.py

      # ===============================
      # Tambahan penting
      # ===============================
      - name: Commit & Push hasil CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/.gitkeep
          git commit -m "Tambah folder data"
          git push
