name: Update Ulasan Playstore

on:
  schedule:
    - cron: '0 18 * * *'   # Jam 01:00 WIB (UTC+7)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode dari repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install library
        run: pip install google-play-scraper pandas

      - name: Jalankan script
        run: python app.py
